### ISSUE TITLE
Working Perfect

### ISSUE THREAD

**Issue by coolerspeex** [Azim-vau/crack-pro#2]
Love You
Improve more :p 👍

**Comment by Azim-vau** [comment]
@coolerspeex 
I will try my best. 
Thank You.

**Comment by coolerspeex** [comment]
also i not get any FOUND all going in Checkpoint is there any tip or you can make it more better to get found

**Comment by coolerspeex** [comment]
in windows its not working

**Comment by Licht-official** [comment]
![Screenshot_2021-04-18-18-23-25-820_com android chrome](https://user-images.githubusercontent.com/82759027/115143814-b0a1a980-a073-11eb-84c3-c7803584c9aa.jpg)



Please add the login token to the crack pro (script / tools) because the login chokies is already an error
