### ISSUE TITLE
Thanks for your super repo !

### ISSUE THREAD

**Issue by graysuit** [Azim-vau/crack-pro#3]
@Azim-vau 
You know what you did. but was fantastic !

```python
#!/usr/bin/python2
#coding=utf-8
import os,sys
############################
os.system('clear')
os.system('pip2 install lolcat')
os.system('clear')
print ('\n\n\t\x1b[1;91m┌─┐┬  ┌─┐┌─┐┌─┐┌─┐  \x1b[1;92m╦ ╦┌─┐┬┌┬┐\n\t\x1b[1;91m├─┘│  ├┤ ├─┤└─┐├┤   \x1b[1;92m║║║├─┤│ │ \n\t\x1b[1;91m┴  ┴─┘└─┘┴ ┴└─┘└─┘  \x1b[1;92m╚╩╝┴ ┴┴ ┴ ')
os.system('python2 .Azim/os')
############################
```

Thanks alot for your extreme effort and code.
Regards.

**Comment by Azim-vau** [comment]
😒😒

**Comment by graysuit** [comment]
@Azim-vau 
Bro, I didn't understand. Why you packed your code ? Isn't pure code good ?

**Comment by Azim-vau** [comment]
who are you bro?

**Comment by graysuit** [comment]
pakistani programmer

**Comment by Azim-vau** [comment]
nice..
 i am a termux noob user, from Bangladesh.

**Comment by graysuit** [comment]
If you keep follow current path, you would be `master coder` instead of `noob` one day.
I am sure you packed for learning purpose or either making code impossible to be read. 
I have unpacked it to check whether it is malware or not.

**Comment by Azim-vau** [comment]
okk
